//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quotes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Quotes
    {
        public int QuoteId { get; set; }
        public string QuoteText { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DateAdded { get; set; }
        public string NameOfAuthor { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Categories Category { get; set; }
    }
}
